### PR TITLE
✨ Show stats in user component

### LINKED ISSUE #55: Extend current user component
image

Stats like `Matches`, `Highlights` and `Likes` should be prepared. The backend logic is not ready and will be implemented afterwards.

### PR DESCRIPTION
**Pull request by lmachens**
fix #55

Logged in:
image

Logged out
image

The stats are placeholders.

### CODE REVIEW

**Review by monavorschulze — APPROVED** [review]
Nice 👍

**Review by AlexisRoe — CHANGES_REQUESTED** [review]
looks fantastic, but we should exchange the defaultAvatar with our mascot and change the green color to the gradient one, dont't you think

**Comment by lmachens** [comment]
> looks fantastic, but we should exchange the defaultAvatar with our mascot and change the green color to the gradient one, dont't you think

I agree that we should replace the default avatar. the color will be replaced in  #66.

**Review by AlexisRoe — APPROVED** [review]
lgtm

**Pull request merged**
